# Generated by Django 2.0 on 2018-02-03 22:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_auto_20171209_0736'), ('core', '0003_auto_20171209_1916'), ('core', '0004_testcase_create_date'), ('core', '0005_auto_20171209_2100'), ('core', '0006_quote')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_title', models.CharField(max_length=200)),
                ('mission_desecription', models.CharField(max_length=10000)),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case_title', models.CharField(max_length=100)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Mission')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('test_case_description', models.CharField(default='(no description)', max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='mission',
            old_name='mission_desecription',
            new_name='mission_description',
        ),
        migrations.AddField(
            model_name='mission',
            name='mission_body',
            field=models.CharField(default='(body missing)', max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
