# Generated by Django 2.0 on 2018-02-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_squashed_0006_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='cite',
            field=models.CharField(default='MythBusters', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testcase',
            name='create_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='test_case_description',
            field=models.CharField(max_length=200),
        ),
    ]
