# Generated by Django 2.0 on 2017-12-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171209_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='mission_body',
            field=models.CharField(default='(body missing)', max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_title',
            field=models.CharField(max_length=100),
        ),
    ]
