# Generated by Django 2.0 on 2017-12-10 01:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171209_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
