# Generated by Django 2.0 on 2017-12-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testcase_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='test_case_description',
            field=models.CharField(default='(no description)', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testcase',
            name='test_case_title',
            field=models.CharField(max_length=100),
        ),
    ]
